export enum QUESTION_TYPES {
  TF = "TF",
  MP1 = "MP1",
  MP2 = "MP2",
  TEXT = "TEXT",
}

export enum QUESTION_DIFFICULTIES {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
}

export enum EXAM_STATUS {
  NOT_STARTED = "NOT_STARTED",
  ONGOING = "ONGOING",
  FINISHED = "FINISHED",
}

export enum SCORES {
  NOSCORE = "NOSCORE",
}

export enum USER {
  INSTRUCTOR = "INSTRUCTOR",
  STUDENT = "STUDENT",
}

export enum LESSON_CATEGORIES {
  BASIC_REQUIRED = "BASIC_REQUIRED",
  BASIC_DIR_INF = "BASIC_DIR_INF",
  BASIC_DIR_TEL = "BASIC_DIR_TEL",
  SELECT_DIR_INF = "SELECT_DIR_INF",
  SELECT_DIR_TEL = "SELECT_DIR_TEL",
  SELECT_INF_TEL = "SELECT_INF_TEL",
}
